### ISSUE TITLE
Building AOSPA For Note 4

### ISSUE THREAD

**Issue by ghost** [AOSPA/android_build#10]
Running kati to generate build-pa_trltexx-clean.ninja...
out/build-pa_trltexx-clean.ninja is missing, regenerating...
build/core/product_config.mk:234: **\* Can not locate config makefile for product "pa_trltexx".
build/core/ninja.mk:163: recipe for target 'out/build-pa_trltexx-clean.ninja' failed
make: **\* [out/build-pa_trltexx-clean.ninja] Error 1

**Comment by Bauuuuu** [comment]
It is not source code problem. You are required to make appropriate changes in the device tree. You can compare the officially supported device tree with yours.
