### ISSUE TITLE
Dex2oatd fail

### ISSUE THREAD

**Issue by Fevax** [AOSPA/android_build#13]
Hey, im porting a new device to your source, samsung galaxy s7 exynos, and i have a problem with dex2oat... can you tell me what could be the problem? I'm building on a VPS server...

log:

FAILED: /bin/bash -c "(mkdir -p out/target/product/hero2lte/obj/APPS/BasicDreams_intermediates/oat/arm64/ && rm -f out/target/product/hero2lte/obj/APPS/BasicDreams_intermediates/oat/arm64/package.odex ) && (find out/target/common/obj/APPS/BasicDreams_intermediates/ -maxdepth 1 -name \"classes*.dex\" | sort | xargs zip -0qjX out/target/product/hero2lte/obj/APPS/BasicDreams_intermediates/oat/arm64/package.odex ) && (mv out/target/product/hero2lte/obj/APPS/BasicDreams_intermediates/oat/arm64/package.odex out/target/product/hero2lte/obj/APPS/BasicDreams_intermediates/oat/arm64/package.odex.input ) && (rm -f out/target/product/hero2lte/obj/APPS/BasicDreams_intermediates/oat/arm64/package.odex ) && (mkdir -p out/target/product/hero2lte/obj/APPS/BasicDreams_intermediates/oat/arm64/ ) && (ANDROID_LOG_TAGS=\"*:e\" out/host/linux-x86/bin/dex2oatd --runtime-arg -Xms64m --runtime-arg -Xmx512m --runtime-arg -classpath --runtime-arg \"&\" --boot-image=out/target/product/hero2lte/dex_bootjars/system/framework/boot.art --dex-file=out/target/product/hero2lte/obj/APPS/BasicDreams_intermediates/oat/arm64/package.odex.input --dex-location=/system/app/BasicDreams/BasicDreams.apk --oat-file=out/target/product/hero2lte/obj/APPS/BasicDreams_intermediates/oat/arm64/package.odex --android-root=out/target/product/hero2lte/system --instruction-set=arm64 --instruction-set-variant=generic --instruction-set-features=default --include-patch-information --runtime-arg -Xnorelocate --no-generate-debug-info --abort-on-hard-verifier-error --no-inline-from=core-oj.jar   --compile-pic ) && (rm out/target/product/hero2lte/obj/APPS/BasicDreams_intermediates/oat/arm64/package.odex.input )"
dex2oatd E 13840 13840 art/runtime/gc/heap.cc:324] Could not create image space with image file 'out/target/product/hero2lte/dex_bootjars/system/framework/boot.art'. Attempting to fall back to imageless running. Error was: Failed to load /system image 'out/target/product/hero2lte/dex_bootjars/system/framework/arm64/boot.art': Failed to mmap at expected address, mapped at 0x68b3e080d000 instead of 0x70000000
dex2oatd E 13840 13840 art/runtime/gc/heap.cc:324] Attempted image: out/target/product/hero2lte/dex_bootjars/system/framework/boot.art
dex2oatd E 13840 13840 art/runtime/runtime.cc:1047] Dex file fallback disabled, cannot continue without image.
dex2oatd E 13840 13840 art/dex2oat/dex2oat.cc:2232] Failed to create runtime

**Comment by TheCrazyLex** [comment]
@raymanfx any idea?

**Comment by xboxfanj** [comment]
@TheCrazyLex dex2oatd isn't used right, since we disabled DEX2OAT_DEBUG? @Fevax are you getting this same error on our latest source?

**Comment by TheCrazyLex** [comment]
Right, dex2oatd shouldn't be there

**Comment by Fevax** [comment]
i will try again later and report

**Comment by Fevax** [comment]
Without dexpreopt i dont have the problem anymore, (still doesn't boot, mkboot/dtbtool are not ready for exynos)

**Comment by TheCrazyLex** [comment]
Closing since old :)
