### ISSUE TITLE
Maintainer for legacy device

### ISSUE THREAD

**Issue by elliot-labs** [AOSPA/android_build#6]
Paranoid android has mentioned that it needs people for maintaining legacy devices.

I am interested in maintaining the D2LTE device(s) if you still need people.

(I know this is not the right place to put it but there was no contact us form on the website)

Thanks!

**Comment by SferaDev** [comment]
Move to http://gerrit.aospal.com and https://github.com/AOSPA-L

Thanks

**Comment by elliot-labs** [comment]
np
